"""Configuration loading for the radar loop."""

from __future__ import annotations

import copy
import json
import pathlib


ROOT = pathlib.Path(__file__).resolve().parents[1]
DEFAULT_SETTINGS_PATH = ROOT / "config" / "settings.example.json"
LOCAL_SETTINGS_PATH = ROOT / "config" / "settings.local.json"


DEFAULT_SETTINGS = {
    "mode": "paper",
    "allow_live_trading": False,
    "account_capabilities": {
        "crypto_derivatives": True,
        "crypto_spot": True,
        "spot_borrow": False,
        "options": False,
        "futures": False,
        "prediction_markets": False,
    },
    "scanner": {
        "scan_universe": 500,
        "review_top": 250,
        "min_base_score": 35.0,
        "max_new_paper_trades": 50,
        "hold_minutes": 60,
        "enable_global_proxy_scan": True,
        "enable_global_market_discovery_scan": True,
        "enable_prediction_market_scan": True,
        "enable_crypto_venue_health_scan": True,
        "global_review_top": 100,
        "global_market_discovery_review_top": 150,
        "prediction_review_top": 100,
        "paper_trade_conditional": True,
        "enable_frontier_crypto_adapter_scan": True,
        "frontier_crypto_review_top": 120,
    },
    "paper_exploration": {
        "enabled": True,
        "synthetic_route_id": "synthetic_research_paper",
        "synthetic_allocation_multiplier": 0.25,
        "diagnose_allocation_multiplier": 0.25,
        "max_stale_minutes": 90.0,
        "zero_admission_revert_loops": 3,
        "guard_value_horizon_minutes": 60,
    },
    "okx_perp_funding_basis_decay_quarantine": {
        "enabled": True,
        "closed_label_limit": 30,
        "duration_days": 14,
        "paper_score_cap": 0.0,
        "min_closed_count": 20,
        "max_avg_pnl_bps": -25.0,
        "max_score_adjustment": -10.0,
        "release_min_avg_pnl_bps": 5.0,
        "release_min_win_rate": 0.50,
    },
    "paper_context_drag": {
        "enabled": True,
        "paper_only": True,
        "min_closed_trades": 8,
        "underperformance_net_edge_bps": 0.0,
        "ranking_penalty_bps_cap": 30.0,
        "minimum_ranking_multiplier": 0.35,
        "delay_decay_bps_per_second": 0.02,
        "max_delay_decay_bps": 8.0,
    },
    "paper_context_priors": {
        "enabled": True,
        "paper_only": True,
        "exceptional_base_signal_score": 85.0,
        "feasibility_standard_prior": 6.0,
        "feasibility_conditional_prior": -10.0,
        "top_rank_min_closed_trades": 25,
        "top_rank_min_avg_pnl_bps": 0.0,
        "top_rank_score_cap": 75.0,
        "conditional_rank_score_cap": 20.0,
        "realized_context_window_closed_trades": 30,
        "realized_context_min_closed_trades": 6,
        "realized_context_positive_scale": 0.2,
        "realized_context_negative_scale": 0.3,
        "realized_context_max_positive_prior": 12.0,
        "realized_context_max_negative_prior": -18.0,
        "realized_context_persistent_negative_closed_trades": 8,
        "realized_context_conditional_penalty_multiplier": 1.75,
        "realized_context_persistent_negative_multiplier": 1.5,
        "strong_liquidity_score": 0.70,
        "strong_liquidity_prior": 4.0,
        "weak_liquidity_score": 0.45,
        "weak_liquidity_prior": -8.0,
        "venue_direction_feasibility_priors": {
            "OKX_SPOT|long|standard": 8.0,
            "OKX_SPOT|long|conditional": 1.0,
            "BYBIT_SPOT|long|standard": 6.0,
            "BYBIT_SPOT|long|conditional": -3.0,
            "GATE|short|standard": 3.0,
            "GATE|short|conditional": -2.0,
            "GATE|long|standard": -7.0,
            "GATE|long|conditional": -10.0,
            "KRAKEN|long|standard": -4.0,
            "KRAKEN|long|conditional": -7.0,
            "MEXC|long|standard": -12.0,
            "MEXC|long|conditional": -15.0,
        },
        "okx_basis_context_overlays": {
            "enabled": True,
            "conditional_long_perp_short_spot_score_cap": 35.0,
            "conditional_long_perp_short_spot_allocation_cap": 0.25,
            "funding_capture_min_closed_trades_for_promotion": 50,
            "funding_capture_score_cap": 75.0,
        },
    },
    "paper_route_feasibility_gate": {
        "enabled": True,
        "min_score": 0.65,
    },
    "paper_route_registry": {
        "enabled": True,
    },
    "paper_context_loss_quarantine": {
        "enabled": True,
        "rolling_window_closed_trades": 30,
        "min_closed_trades": 12,
        "max_expectancy_bps": 0.0,
        "max_win_rate": 0.45,
        "max_tail_average_bps": -20.0,
        "max_worst_loss_bps": -80.0,
        "cooldown_hours": 24,
        "recovery_min_closed_trades": 8,
        "recovery_min_expectancy_bps": 0.0,
        "recovery_min_win_rate": 0.50,
        "recovery_min_tail_average_bps": -20.0,
    },
    "paper_context_cost_floor": {
        "enabled": True,
        "min_net_edge_buffer_bps": 2.0,
        "safety_multiplier": 1.25,
        "base_cost_bps": 1.0,
        "spread_weight": 1.0,
        "default_half_spread_bps": 2.0,
        "default_slippage_bps": 3.0,
        "surface_costs": {
            "proxy": {"slippage_bps_per_side": 1.5, "fee_bps_per_side": 0.5},
            "frontier": {"slippage_bps_per_side": 3.0, "fee_bps_per_side": 1.0},
            "carry": {"slippage_bps_per_side": 2.0, "fee_bps_per_side": 1.0},
        },
        "default_latency_decay_bps": 0.0,
        "latency_decay_bps_per_window": 1.0,
        "max_latency_decay_bps": 12.0,
        "default_carry_bps_horizon": 0.0,
        "missing_carry_bps_horizon": 2.0,
        "carry_horizon_hours": 8.0,
        "default_volatility_tail_buffer_bps": 1.0,
        "frontier_tail_buffer_bps": 2.0,
        "gap_risk_weight": 0.10,
        "max_gap_risk_buffer_bps": 10.0,
        "funding_instability_weight": 0.50,
        "max_funding_instability_buffer_bps": 8.0,
        "max_liquidity_penalty_bps": 6.0,
        "volatility_weight": 0.08,
        "max_volatility_penalty_bps": 12.0,
        "freshness_penalty_bps_per_window": 2.0,
        "max_freshness_penalty_bps": 12.0,
        "frontier_freshness_window_seconds": 30.0,
        "proxy_freshness_window_seconds": 900.0,
        "carry_freshness_window_seconds": 30.0,
        "frontier_max_signal_age_seconds": 90.0,
        "proxy_max_signal_age_seconds": 900.0,
        "carry_max_signal_age_seconds": 30.0,
        "extra_leg_cost_bps": 4.0,
        "missing_spread_penalty_bps": 4.0,
        "missing_liquidity_penalty_bps": 3.0,
        "missing_freshness_penalty_bps": 2.0,
        "conditional_route_penalty_bps": 4.0,
        "paper_proxy_route_penalty_bps": 6.0,
        "unknown_route_penalty_bps": 8.0,
        "proxy_short_min_liquidity_score": 0.65,
        "proxy_short_max_freshness_age_seconds": 900.0,
        "frontier_long_min_liquidity_score": 0.35,
        "frontier_long_max_freshness_age_seconds": 90.0,
        "minimum_score_multiplier": 0.5,
        "context_transfer_scoring": {
            "enabled": True,
            "distance_penalty": 0.30,
            "minimum_multiplier": 0.15,
            "synthetic_route_multiplier": 0.80,
            "secondary_venue_multiplier": 0.85,
            "product_type_mismatch_multiplier": 0.85,
            "secondary_venue_short_multiplier": 0.85,
            "near_trade_threshold_score": 50.0,
            "near_threshold_band": 10.0,
            "near_threshold_allocation_multiplier": 0.50,
        },
        "context_attribution_scoring": {
            "enabled": True,
            "venue_quality_floor_multiplier": 0.65,
            "liquidity_floor_multiplier": 0.65,
            "regime_stability_floor_multiplier": 0.65,
            "spread_burden_scale_bps": 25.0,
            "max_spread_burden_penalty": 0.25,
            "carry_burden_scale_bps": 25.0,
            "max_carry_burden_penalty": 0.25,
            "max_signal_age_penalty": 0.25,
        },
    },
    "yahoo_proxy_reuse_gate": {
        "enabled": True,
        "max_quote_age_seconds": 1200.0,
        "max_expected_bar_lag_seconds": 120.0,
        "default_bar_interval_seconds": 900.0,
        "min_opening_gap_bps": 40.0,
        "min_opening_gap_followthrough_ratio": 0.25,
    },
    "yahoo_proxy_momentum_context": {
        "enabled": True,
        "paper_only": True,
        "minimum_move_strength_bps": 40.0,
        "minimum_tradable_followthrough_bps": 5.0,
        "max_freshness_age_seconds": 900.0,
        "minimum_volatility_normalized_persistence": 0.75,
        "ranking_penalty_points": 15.0,
        "minimum_counterfactual_allocation_multiplier": 0.25,
    },
    "yahoo_proxy_cross_surface_alignment_guard": {
        "enabled": True,
        "max_destination_spread_bps": 8.0,
        "min_destination_liquidity_score": 0.65,
        "min_native_proxy_momentum_bps": 5.0,
        "min_native_proxy_regime_windows": 3,
        "min_native_proxy_positive_window_rate": 0.67,
        "quarantined_target_surfaces": ["OKX_SPOT", "OKX_PERP"],
        "allow_native_proxy_monitoring": True,
        "min_target_surface_closed_count": 20,
        "min_target_surface_expectancy_net_bps": 0.0,
        "min_target_surface_quality_rate": 0.5,
        "max_target_surface_evidence_age_hours": 168.0,
        "min_realized_transfer_windows": 3,
        "min_realized_transfer_positive_window_rate": 0.67,
        "reenable_condition": (
            "stable_positive_realized_paper_outcomes_for_same_source_target_mapping_and_"
            "native_proxy_regime_and_local_frontier_confirmation"
        ),
    },
    "paper_portability_quarantine": {
        "enabled": True,
        "min_closed_count": 20,
        "min_expectancy_net_bps": 0.0,
        "neutral_score": 0.0,
    },
    "paper_cell_policy": {
        "min_closed_trades": 3,
        "probation_ttl_days": 7,
        "promote_min_avg_pnl_bps": 1.0,
        "promote_min_win_rate": 0.5,
        "revert_avg_pnl_bps": -5.0,
        "asymmetric_direction_min_closed_trades": 20,
        "asymmetric_direction_min_avg_pnl_bps": 1.0,
        "conditional_frontier_short_min_closed_trades": 12,
        "conditional_frontier_short_min_avg_pnl_bps": 1.0,
        "conditional_frontier_short_confidence_target_closed_trades": 20,
        "conditional_frontier_short_min_promotion_confidence": 0.8,
        "conditional_frontier_short_confidence_penalty_bps": 2.0,
        "proxy_short_min_liquidity_score": 0.65,
        "proxy_short_max_freshness_age_seconds": 900.0,
        "frontier_long_min_liquidity_score": 0.35,
        "frontier_long_max_freshness_age_seconds": 90.0,
        "allowed_promotion_route_statuses": ["standard", "feasible", "executable"],
    },
    "global_market_discovery_scanner": {
        "enabled": True,
        "active_paper_cohort_enabled": True,
        "min_discovery_priority": 70,
        "max_surfaces_per_cycle": 28,
        "max_proxy_symbols_per_surface": 4,
        "recent_discovery_rotation_slots": 8,
        "workers": 12,
        "merge_default_seeds": True,
        "watch_only_stale_minutes": 180,
        "priceable_candidate_score_floor": 42.0,
        "paper_quote_context": {
            "enabled": True,
            "paper_only": True,
            "stale_quote_age_ms": 900000.0,
            "wide_spread_bps": 8.0,
            "shallow_depth_notional": 100000.0,
            "stale_penalty_points_cap": 8.0,
            "wide_penalty_points_cap": 6.0,
            "shallow_penalty_points_cap": 4.0,
            "synthetic_route_penalty_points": 3.0,
            "total_penalty_points_cap": 16.0,
        },
    },
    "paper_hold_optimizer": {
        "enabled": True,
        "default_hold_minutes": 60,
        "candidate_horizons_minutes": [5, 15, 60, 240],
        "min_samples": 12,
        "min_avg_uplift_bps": 2.0,
        "switch_uplift_bps": 6.0,
        "max_horizon_steps_per_update": 1,
        "recency_weighting_enabled": True,
        "recency_half_life_days": 3.0,
        "confidence_adjustment_enabled": True,
        "confidence_target_effective_samples": 48.0,
        "confidence_floor": 0.25,
        "prefer_shorter_on_tie_bps": 1.0,
        "group_hierarchy": ["signal_key", "venue_trade_direction", "trade_direction"],
    },
    "frontier_crypto_adapter": {
        "enabled": True,
        "timeout_seconds": 8,
        "min_dislocation_bps": 12.0,
        "bybit_region_blocked_probe_interval_seconds": 300,
        "intraday_features_enabled": True,
        "intraday_feature_timeout_seconds": 4,
        "intraday_feature_workers": 6,
        "intraday_feature_max_observations": 24,
        "intraday_feature_max_per_venue": 6,
        "marketability_gates": {
            "enabled": True,
            "paper_only": True,
            "diagnostic_only": True,
            "confirmed_route_allocation_multiplier": 1.0,
            "conservative_route_allocation_multiplier": 0.25,
            "max_book_age_seconds": 30.0,
            "max_spread_bps": 8.0,
            "min_top_of_book_notional_usd": 1000.0,
            "max_cross_venue_deviation_bps": 250.0,
            "min_reference_venues": 1,
            "min_route_confidence": 0.70,
            "min_venue_health_score": 60.0,
            "known_paper_route_statuses": ["standard"],
        },
        "dislocation_quality": {
            "enabled": True,
            "paper_only": True,
            "reference_breadth_target": 3,
            "max_leave_one_out_shift_bps": 25.0,
            "freshness_target_seconds": 30.0,
            "freshness_max_seconds": 90.0,
            "ranking_quality_weight": 0.35,
            "reference_breadth_weight": 0.25,
            "reference_stability_weight": 0.30,
            "cost_efficiency_weight": 0.30,
            "freshness_weight": 0.15,
        },
        "secondary_cex_strength": {
            "enabled": True,
            "preferred_venues": ["BITGET", "WHITEBIT", "OKX_SPOT"],
            "comparable_venues": ["GATE", "MEXC", "KUCOIN", "BYBIT_SPOT"],
            "minimum_momentum_confirmation_count": 2,
        },
        "long_entry_confirmation": {
            "enabled": True,
            "paper_only": True,
            "entry_confidence_min": 0.72,
            "minimum_momentum_confirmation_count": 2,
            "minimum_venue_strength_score": 55.0,
            "require_price_above_vwap": True,
            "allocation_cap": 0.25,
            "ranking_score_cap": 59.999,
            "max_spread_bps": 8.0,
            "min_relative_volume_1m_60m": 0.75,
        },
        "effective_edge": {
            "enabled": True,
            "paper_only": True,
            "minimum_effective_edge_bps": 0.0,
            "max_freshness_age_seconds": 90.0,
            "freshness_penalty_window_seconds": 30.0,
            "freshness_penalty_bps_per_window": 2.0,
            "max_freshness_penalty_bps": 12.0,
            "min_liquidity_score": 0.35,
            "min_venue_reliability_score": 0.60,
            "max_venue_reliability_penalty_bps": 5.0,
            "external_quote_conversion_cost_bps": 4.0,
            "synthetic_proxy_drag_bps": 4.0,
            "allocation_edge_bps_cap": 24.0,
            "synthetic_allocation_cap": 0.25,
            "low_reliability_allocation_cap": 0.50,
            "low_reliability_score": 0.70,
            "counterfactual_allocation_multiplier": 0.25,
        },
        "short_cost_decomposition": {
            "enabled": True,
            "paper_only": True,
            "venue_quality_penalty_bps_cap": 8.0,
            "missing_venue_quality_penalty_bps": 6.0,
            "synthetic_route_penalty_bps": 6.0,
            "unconfirmed_borrow_proxy_penalty_bps": 6.0,
            "allocation_edge_bps_cap": 24.0,
        },
        "short_market_context": {
            "enabled": True,
            "paper_only": True,
            "minimum_reference_breadth": 3,
            "max_spread_plus_slippage_to_edge_ratio": 1.0,
            "min_broader_risk_off_ratio": 0.60,
            "minimum_local_reversal_bps": 1.0,
            "ranking_weight": 0.20,
            "minimum_counterfactual_allocation_multiplier": 0.25,
        },
        "paper_quote_context": {
            "enabled": True,
            "paper_only": True,
            "stale_quote_age_ms": 90000.0,
            "wide_spread_bps": 12.0,
            "shallow_depth_notional": 1000.0,
            "stale_penalty_points_cap": 8.0,
            "wide_penalty_points_cap": 6.0,
            "shallow_penalty_points_cap": 4.0,
            "synthetic_route_penalty_points": 3.0,
            "total_penalty_points_cap": 16.0,
        },
    },
    "frontier_data_quality": {
        "enabled": True,
        "adaptive_selection": True,
        "max_symbols_per_cycle": 180,
        "max_symbols_per_venue": 24,
        "known_quality_rate_target": 0.25,
        "quality_target_escalation_enabled": True,
        "quality_target_extra_symbols_per_cycle": 120,
        "quality_target_max_symbols_per_cycle": 300,
        "quality_target_max_symbols_per_venue": 32,
        "quality_target_starved_venue_reserve_per_cycle": 90,
        "unknown_quality_reserve_per_cycle": 60,
        "regional_reserve_per_cycle": 50,
        "exploit_variant_reserve_per_cycle": 35,
        "regional_shadow_depth_probe_enabled": False,
        "regional_shadow_depth_probe_max_per_cycle": 15,
        "regional_shadow_depth_probe_max_per_region": 5,
        "regional_shadow_depth_probe_max_per_venue": 3,
        "regional_shadow_depth_probe_max_spread_bps": 75.0,
        "regional_shadow_depth_probe_allowed_quote_normalization_statuses": [
            "usd_like",
            "same_venue_stablecoin_reference",
        ],
        "zero_quality_venue_probe_reserve_per_cycle": 24,
        "zero_quality_venue_probe_per_venue": 6,
        "zero_quality_venue_probe_min_observation_count": 10,
        "zero_quality_venue_probe_max_known_quality_count": 1,
        "zero_quality_venue_probe_max_spread_bps": 50.0,
        "data_gap_depth_quota_fraction": 0.2,
        "data_gap_depth_quota_max_per_cycle": 12,
        "data_gap_depth_quota_min_observation_count": 1,
        "data_gap_known_quality_rate_threshold": 0.02,
        "active_variant_enrichment_top": 10,
        "shadow_variant_enrichment_top": 2,
        "shadow_variant_enrichment_variant_cap": 8,
        "starved_venues": [
            "BITGET",
            "KRAKEN",
            "COINBASE",
            "MEXC",
            "BYBIT_SPOT",
            "OKX_SPOT",
            "KUCOIN",
            "GATE",
            "BINANCE_US",
            "LUNO",
            "VALR",
            "BITSO",
            "BUDA",
            "MERCADO_BITCOIN",
            "INDODAX",
            "BITKUB",
            "COINJAR",
            "RIPIO",
            "WHITEBIT",
        ],
        "starved_venue_min_depth_per_cycle": 4,
        "venue_depth_minimums": {
            "BITSO": 8,
            "COINBASE": 8,
            "KRAKEN": 8,
            "KUCOIN": 8,
            "GATE": 8,
            "BYBIT_SPOT": 8,
            "BINANCE_US": 8,
            "MEXC": 12,
            "BITGET": 12,
            "OKX_SPOT": 16,
            "LUNO": 16,
            "VALR": 16,
            "INDODAX": 16,
            "MERCADO_BITCOIN": 8,
            "BUDA": 8,
            "BITKUB": 8,
            "COINJAR": 8,
            "RIPIO": 1,
            "WHITEBIT": 12,
        },
        "depth_levels": 50,
        "workers": 16,
        "timeout_seconds": 6,
        "notionals_usd": [100.0, 250.0, 1000.0],
        "conservative_fee_bps_per_side": 10.0,
        "fresh_seconds": 30.0,
        "block_stale_seconds": 90.0,
        "shadow_below_score": 35.0,
        "conditional_below_score": 60.0,
        "min_verified_snapshots_for_regional_candidate": 3,
        "min_regional_quality_score": 70.0,
        "snapshot_retention_rows": 100000,
        "valid_empty_book_cooldown_after": 2,
        "empty_book_core_asset_exemptions": ["BTC", "ETH", "USDT", "USDC"],
    },
    "frontier_regional_fx": {
        "enabled": True,
        "cache_ttl_minutes": 5,
        "yahoo_fallback_enabled": True,
        "yahoo_cache_ttl_minutes": 2,
        "max_reference_age_hours": 30,
        "timeout_seconds": 10,
        "quotes": ["ARS", "AUD", "BRL", "CLP", "COP", "EUR", "GBP", "GHS", "IDR", "KES", "MXN", "MYR", "NGN", "PEN", "PHP", "SGD", "THB", "TZS", "UGX", "ZAR"],
    },
    "public_market_adapters": {
        "enabled": True,
        "workers": 5,
        "twse_daily_public": {"enabled": True, "cache_minutes": 60, "max_instruments": 300},
        "kase_futures_public_results": {"enabled": True, "cache_minutes": 15},
        "kazakhstan_stock_exchange_kase_global": {"enabled": True, "cache_minutes": 60},
        "nzx_gdt_event_reference": {"enabled": True, "cache_minutes": 60},
        "bursa_derivatives_contract_catalog": {"enabled": True, "cache_minutes": 360},
        "bahrain_cross_listings_catalog": {"enabled": True, "cache_minutes": 360},
        "gemini_prediction_markets_btc_5m": {
            "enabled": True,
            "cache_minutes": 0,
            "event_limit": 50,
            "timeout_seconds": 12,
        },
        "whitebit_perpetuals_public": {
            "enabled": True,
            "cache_minutes": 2,
            "max_instruments": 120,
            "max_depth_books": 16,
            "depth_levels": 50,
        },
        "deribit_derivatives_public": {
            "enabled": True,
            "cache_minutes": 2,
            "currencies": ["BTC", "ETH", "USDC"],
            "max_futures_per_currency": 40,
            "max_options_per_currency": 40,
            "max_depth_books": 6,
            "depth_levels": 20,
        },
    },
    "derivatives_market_adapters": {
        "min_abs_funding_bps": 3.0,
        "min_net_carry_edge_bps": 2.0,
        "min_quality_score": 60.0,
        "fee_bps_per_side": 5.0,
        "slippage_bps_per_side": 3.0,
    },
    "market_admission": {
        "enabled": True,
        "bridge_max_actions_per_loop": 50,
        "consecutive_failures_degraded": 5,
        "diagnostic_after_eligible_scans": 30,
        "implementation_task_after_eligible_scans": 120,
        "proxy_short_quality_gate": {
            "enabled": True,
            "max_freshness_age_seconds": 3600.0,
            "min_depth_notional_usd": 1.0,
            "min_liquidity_score": 0.65,
        },
        "requested_symbols": [
            "VIXY", "VXX", "UVXY", "SVXY", "EWY", "PKX", "EWT", "TSM", "UMC",
            "EWZ", "NU", "SHOP", "TD", "RY", "GLD", "SLV", "SPY", "EWJ", "BHP",
        ],
    },
    "risk": {
        "min_liquidity_score": 0.35,
        "max_spread_bps": 8.0,
        "min_net_edge_bps": 2.0,
        "max_abs_24h_move_pct": 60.0,
        "taker_fee_bps_per_leg": 5.0,
        "slippage_bps_per_leg": 3.0,
        "max_open_paper_trades": 500,
    },
    "learning": {
        "enabled": True,
        "min_samples_for_adjustment": 3,
        "conditional_frontier_short_min_samples_for_adjustment": 20,
        "max_adjustment_bps": 15.0,
        "score_adjustment_scale": 0.35,
        "horizon_minutes": [5, 15, 60, 240, 1440],
        "max_outcome_delay_seconds": 300,
    },
    "agent_memory": {
        "enabled": True,
        "retrieval_mode": "hybrid_temporal_fts_graph",
        "retrieval_limit_per_agent": 24,
        "retrieval_candidate_pool": 160,
        "max_memory_summary_chars": 800,
        "historical_context_fraction": 0.17,
        "graph_relation_bonus": 0.08,
        "preferred_namespace_fraction": 0.67,
        "recency_half_life_days": 14.0,
        "profile_version_hours": 6.0,
        "minimum_importance": 0.15,
        "legacy_bootstrap_enabled": True,
        "legacy_bootstrap_limit": 20000,
        "retrieval_log_retention_rows": 10000,
        "checkpoint_enabled": True,
        "checkpoint_path": "runs/langgraph_checkpoints.sqlite",
        "checkpoint_retention_cycles": 48,
        "checkpoint_max_storage_mb": 64,
        "checkpoint_compact_on_prune": True,
        "checkpoint_vacuum_min_reclaim_mb": 16,
        "graphiti": {
            "mode": "auto",
            "uri_env": "GRAPHITI_URI",
            "user_env": "GRAPHITI_USER",
            "password_env": "GRAPHITI_PASSWORD",
            "minimum_importance": 0.8,
            "max_episodes_per_cycle": 10,
            "search_enabled": True,
            "max_search_results_per_agent": 6,
        },
    },
    "signal_redesign": {
        "enabled": True,
        "evaluation_horizon_mode": "best_reliable",
        "candidate_horizons_minutes": [5, 15, 60, 240, 1440],
        "horizon_switch_uplift_bps": 6.0,
        "bootstrap_exact_max_pairs": 2000,
        "trial_cadence_minutes": 15,
        "min_paired_trials": 30,
        "min_observation_hours": 48,
        "min_valid_label_rate": 0.95,
        "max_outcome_delay_seconds": 300,
        "min_opportunity_coverage": 0.30,
        "min_paired_uplift_bps": 5.0,
        "max_win_rate_decline": 0.05,
        "max_worst_decile_regression_bps": 50.0,
        "revert_regression_bps": 8.0,
        "consecutive_passes_to_promote": 2,
        "max_trials_per_loop": 160,
        "max_trials_per_variant_per_loop": 12,
        "max_trials_per_venue_per_loop": 20,
        "min_shadow_trial_quality_score": 35.0,
        "exclude_shadow_trials_with_critical_anomalies": True,
    },
    "strategy_lab": {
        "enabled": True,
        "observation_programs_enabled": True,
        "promoted_signal_plugins_enabled": True,
        "feature_snapshot_minutes": 5,
        "feature_snapshot_retention_days": 14,
        "feature_snapshot_max_rows": 2_000_000,
        "feature_history_max_points": 4032,
        "max_candidates_per_loop": 100,
        "max_candidates_per_experiment": 10,
        "runtime_review_reserved_slots": 50,
        "candidate_score_bonus": 1.0,
        "max_candidate_score_bonus": 5.0,
        "evaluation_horizon_minutes": 60,
        "evaluation_horizon_mode": "best_reliable",
        "candidate_horizons_minutes": [5, 15, 60, 240, 1440],
        "horizon_switch_uplift_bps": 6.0,
        "expand_min_labels": 12,
        "expand_min_avg_pnl_bps": 6.0,
        "expand_min_win_rate": 0.52,
        "promote_min_labels": 30,
        "promote_min_active_hours": 48.0,
        "promote_min_avg_pnl_bps": 10.0,
        "promote_min_win_rate": 0.53,
        "promote_min_valid_label_rate": 0.90,
        "promote_worst_decile_floor_bps": -45.0,
        "retire_min_labels": 20,
        "retire_max_avg_pnl_bps": -8.0,
        "retire_max_win_rate": 0.43,
        "consecutive_passes_to_promote": 2,
        "adaptive_relaxation": {
            "enabled": True,
            "mode": "aggressive_discovery",
            "min_eligible_scans": 6,
            "min_eligible_observations": 250,
            "max_gates_per_revision": 3,
            "minimum_gate_percentile": 0.25,
            "maximum_gate_percentile": 0.75,
            "critical_max_spread_bps": 50.0,
            "paper_allocation_multiplier": 0.10,
            "max_new_children_per_loop": 3,
            "max_lineage_depth": 2,
        },
        "yahoo_proxy_momentum_source_veto": {
            "min_recovery_windows": 3,
            "min_samples_per_window": 10,
            "min_diagnostic_pass_rate": 0.90,
            "recovery_evidence": {},
        },
        "yahoo_proxy_momentum_freshness_shadow_gate": {
            "enabled": True,
            "max_quote_age_seconds": 1200.0,
            "max_last_trade_age_seconds": 1200.0,
            "min_tick_observations": 2,
            "min_tick_move_bps": 3.0,
            "min_alignment_ratio": 0.5,
        },
        "lineage_source_health_guard": {
            "enabled": True,
            "negative_edge_floor_bps": 0.0,
            "penalty_min_closed_count": 3,
            "min_closed_count": 10,
            "penalty_score_multiplier": 0.50,
        },
    },
    "okx_signal_research": {
        "enabled": True,
    },
    "prediction_market_scanner": {
        "orderbook_enrichment_top": 30,
        "provider_market_cap": 100,
        "polymarket_market_cap": 100,
        "polymarket_paper_gate_enabled": True,
        "polymarket_require_visible_book": True,
        "polymarket_require_freshness_timestamp": True,
        "polymarket_max_stale_minutes": 15,
        "polymarket_max_future_clock_skew_minutes": 5,
        "polymarket_max_days_to_resolution": 30,
        "polymarket_min_liquidity_usd": 1_000,
        "polymarket_max_spread_bps": 300,
        "kalshi_market_cap": 50,
        "kalshi_fetch_pages": 3,
        "kalshi_min_hours_to_resolution": 2,
        "kalshi_max_days_to_resolution": 30,
        "kalshi_min_liquidity_usd": 1_000,
        "kalshi_max_spread_bps": 500,
        "kalshi_max_stale_minutes": 15,
        "kalshi_fee_proxy_bps": 15,
        "kalshi_min_model_edge_bps": 25,
        "kalshi_fair_value_prior": 0.50,
        "kalshi_market_shrinkage": 0.70,
    },
    "self_improvement": {
        "enabled": True,
        "process_code_changes_in_radar_loop": False,
        "max_tasks_per_loop": 5,
        "max_policies_per_task": 5,
        "default_policy_trade_ttl": 30,
        "min_eval_closed_trades": 10,
        "promote_min_improvement_bps": 3.0,
        "revert_max_regression_bps": 8.0,
    },
    "llm_bridge": {
        "enabled": True,
        "ingest_recommendations": True,
        "max_recommendations_per_loop": 20,
        "allowed_actions": [
            "propose_build_task",
            "propose_growth_experiment",
            "propose_hunter_directive",
            "request_data_source",
            "request_market_adapter",
            "request_red_team",
            "propose_signal_variant",
            "propose_diagnostic_hypothesis",
            "propose_strategy_lab_experiment",
            "propose_code_change",
            "spawn_agent",
        ],
    },
    "llm_swarm": {
        "enabled": True,
        "auto_run": True,
        "run_in_radar_loop": False,
        "min_minutes_between_runs": 10,
        "max_recommendations_per_run": 20,
        "write_fallback_recommendations_to_inbox": False,
        "cooldown_on_model_unavailable": True,
        "model_failure_cooldown_minutes": 60,
    },
    "dynamic_agents": {
        "enabled": True,
        "bootstrap_seed_agents": True,
        "agent_architect_enabled": True,
        "max_new_agents_per_cycle": 1,
        "spawn_cluster_min_count": 3,
        "spawn_objective_overlap_threshold": 0.82,
        "evidence_delta_triggers": True,
        "adaptive_concurrency": 8,
        "minimum_concurrency": 1,
        "latency_backoff_seconds": 120,
        "memory_backoff_percent": 85,
        "report_limit": 100,
    },
    "evolution_worker": {
        "enabled": True,
        "interval_seconds": 300,
        "defer_generic_builder_when_targeted_code_attempted": True,
    },
    "codex_worker_pool": {
        "enabled": True,
        "coordination_db": "runs/codex_coordination.sqlite",
        "max_workers": 3,
        "max_verifiers": 2,
        "work_stealing": True,
        "task_lease_seconds": 2700,
        "worker_heartbeat_seconds": 30,
        "promotion_lease_seconds": 180,
        "verification_timeout_seconds": 900,
        "queue_batch_size": 100,
        "max_quick_task_hops": 8,
        "quick_task_seconds": 5,
        "promotion_reconcile_log_limit": 500,
        "defer_full_regression": True,
        "keep_repairing_after_verification_failure": True,
        "revert_only_on_catastrophic_health_failure": True,
        "worker_roles": [
            {"worker_id": "strategy-codex", "preferred_lanes": ["strategy", "activation", "adapter", "general"]},
            {"worker_id": "market-codex", "preferred_lanes": ["adapter", "activation", "strategy", "general"]},
            {"worker_id": "system-codex", "preferred_lanes": ["general", "activation", "adapter", "strategy"]},
        ],
    },
    "adapter_implementation_owner": {
        "enabled": True,
        "min_minutes_between_attempts": 15,
        "scan_limit": 100,
    },
    "market_activation_owner": {
        "enabled": True,
        "max_new_tasks_per_cycle": 100,
        "max_strategy_handoffs_per_cycle": 20,
        "lease_seconds": 2400,
        "retry_backoff_seconds": 300,
        "runtime_verification_scans": 3,
        "minimum_price_observations": 1,
        "trade_evidence_lookback_rows": 10000,
        "report_limit": 100,
    },
    "strategy_implementation_owner": {
        "enabled": True,
        "lease_seconds": 2400,
        "retry_backoff_seconds": 300,
        "memory_context_chars": 70000,
        "memory_retrieval_limit": 80,
        "salvage_invalid_backlog": True,
        "salvage_limit_per_cycle": 12,
        "stalled_testing_hours": 24,
        "minimum_concurrent_experiments": 8,
        "contract_intake_enabled": True,
        "contract_intake_batch_size": 6,
        "contract_intake_model_tier": "standard",
        "contract_intake_reasoning_effort": "medium",
        "contract_intake_timeout_seconds": 180,
        "contract_intake_max_output_tokens": 9000,
        "report_limit": 100,
    },
    "research_worker": {
        "enabled": True,
        "global_market_discovery": True,
        "web_research_enabled": True,
        "run_every_evolution_cycle": True,
        "bootstrap_seed_catalog_once": True,
        "search_themes_per_cycle": 2,
        "search_theme_cooldown_hours": 168,
        "max_web_discoveries_per_cycle": 8,
        "require_public_source_urls": True,
        "model_tier": "fast",
        "reasoning_effort": "low",
        "max_output_tokens": 5000,
        "timeout_seconds": 120,
        "max_candidates_per_run": 80,
        "max_artifacts_per_run": 20,
        "artifact_priority_floor": 70,
        "discovery_seeds": [],
    },
    "autonomous_builder": {
        "enabled": True,
        "auto_run": True,
        "run_in_radar_loop": False,
        "min_minutes_between_runs": 20,
        "lock_stale_minutes": 180,
        "model_tier": "standard",
        "plan_max_context_chars": 35000,
        "implementation_report_context_chars": 12000,
        "plan_timeout_seconds": 240,
        "implementation_timeout_seconds": 240,
        "plan_reasoning_effort": "medium",
        "implementation_reasoning_effort": "medium",
        "max_context_chars": 70000,
        "max_report_chars": 12000,
        "max_code_file_chars": 12000,
        "plan_max_output_tokens": 12000,
        "max_output_tokens": 12000,
        "implementation_strategy": "code_evolution_handoff",
        "require_unified_diff": True,
    },
    "codex_repo_agent": {
        "enabled": True,
        "model": "gpt-5.4",
        "reasoning_effort": "high",
        "parallel_sessions_enabled": True,
        "session_lock_dir": "runs/codex_session_locks",
        "timeout_seconds": 1800,
        "resume_cooldown_seconds": 300,
        "max_resumes_per_cycle": 1,
        "post_promotion_health_grace_seconds": 600,
        "post_promotion_health_loops": 3,
        "runtime_package": "openai-codex==0.144.4",
        "npm_runtime_package": "@openai/codex@0.146.0",
        "npm_fallback_enabled": True,
        "auto_install_npm_fallback": False,
        "network_access": True,
        "api_key_envs": ["CODEX_API_KEY", "OPENAI_API_KEY"],
        "codex_home": "~/.codex",
        "chatgpt_account_fallback_enabled": True,
        "fallback_on_api_quota": True,
    },
    "code_evolution": {
        "enabled": True,
        "git_release_enabled": True,
        "run_candidate_canary": False,
        "promote_candidate_after_canary": True,
        "workspace_status_names": True,
        "auto_merge_paper_only": True,
        "max_auto_merges_per_loop": 12,
        "require_frontier_model": False,
        "required_model": "openai/gpt-5.4",
        "min_priority": 50,
        "run_full_regression": True,
        "full_regression_timeout_seconds": 300,
        "probation_loops": 1,
        "rollback_on_health_failure": True,
        "generate_patch_when_missing": True,
        "local_context_patch_apply": True,
        "repair_patch_when_apply_fails": True,
        "repair_patch_when_sandbox_fails": True,
        "patch_repair_attempts": 3,
        "repair_unknown_paths": True,
        "validate_test_commands": True,
        "reject_orphan_helpers": True,
        "patch_generation_max_file_chars": 20000,
        "patch_generation_max_output_tokens": 16000,
        "install_changed_python_dependencies": True,
        "standard_patch_tier": "fast",
        "high_quality_patch_tier": "standard",
        "high_quality_patch_min_score": 88,
        "repair_patch_tier": "fast",
        "frontier_patch_tier": "frontier",
        "frontier_required_priority": 98,
        "frontier_required_categories": [
            "evolution_loop_improvement",
        ],
        "frontier_waste_guard_enabled": True,
        "frontier_waste_guard_recent": 12,
        "frontier_waste_guard_after": 8,
        "frontier_waste_guard_min_quality": 55,
    },
    "okx_carry_economics": {
        "default_funding_interval_hours": 8.0,
        "default_taker_fee_bps_per_leg": 5.0,
        "default_slippage_bps_per_leg": 3.0,
        "unknown_borrow_cost_penalty_bps": 25.0,
        "min_positive_net_carry_bps": 3.0,
    },
    "hunter_directive_hygiene": {
        "enabled": True,
    },
    "hunter_allocation": {
        "enabled": True,
        "apply_to_candidate_review": True,
        "buckets": {"exploit": 0.5, "explore": 0.3, "diagnose": 0.2},
    },
    "route_unblocker": {
        "enabled": True,
        "allow_paper_proxy_routes": True,
        "spot_borrow_proxy_allocation_multiplier": 0.25,
        "prediction_market_research_allocation_multiplier": 0.10,
    },
    "signal_safety": {
        "enabled": True,
        "min_closed_for_action": 5,
        "recent_trade_window": 10,
        "quarantine_recent_avg_bps": -100.0,
        "quarantine_lifetime_avg_bps": -250.0,
        "quarantine_worst_bps": -1000.0,
        "quarantine_win_rate": 0.30,
        "demote_recent_avg_bps": -20.0,
        "demote_lifetime_avg_bps": -50.0,
        "demote_win_rate": 0.30,
        "recovery_probe_every_reviews": 25,
        "recovery_probe_allocation_multiplier": 0.10,
        "probation_allocation_multiplier": 0.25,
        "release_min_recovery_trades": 5,
        "release_min_avg_pnl_bps": 10.0,
        "release_min_win_rate": 0.55,
        "release_max_worst_bps": -500.0,
    },
    "contextual_failure_filters": {
        "enabled": True,
        "create_policies": True,
        "min_closed_for_filter": 5,
        "max_new_policies_per_loop": 3,
        "max_active_policies_per_signal": 4,
        "default_policy_trade_ttl": 30,
        "policy_priority": 91,
        "recovery_probe_every_reviews": 25,
        "recovery_probe_allocation_multiplier": 0.10,
        "release_min_recovery_trades": 5,
        "release_min_avg_pnl_bps": 10.0,
        "release_min_win_rate": 0.55,
        "release_max_worst_bps": -500.0,
        "cross_context_failure_allocation_multiplier": 0.25,
        "cross_context_failure_score_multiplier": 0.75,
    },
}


def deep_merge(base: dict, override: dict) -> dict:
    result = copy.deepcopy(base)
    for key, value in override.items():
        if isinstance(value, dict) and isinstance(result.get(key), dict):
            result[key] = deep_merge(result[key], value)
        else:
            result[key] = value
    return result


def load_settings(path: str | pathlib.Path | None = None) -> dict:
    if path is None:
        path = DEFAULT_SETTINGS_PATH
    config_path = pathlib.Path(path)
    if not config_path.exists():
        settings = copy.deepcopy(DEFAULT_SETTINGS)
    else:
        loaded = json.loads(config_path.read_text(encoding="utf-8-sig"))
        settings = deep_merge(DEFAULT_SETTINGS, loaded)
    if path == DEFAULT_SETTINGS_PATH and LOCAL_SETTINGS_PATH.exists():
        local_loaded = json.loads(LOCAL_SETTINGS_PATH.read_text(encoding="utf-8-sig"))
        settings = deep_merge(settings, local_loaded)
    return settings

