"""Configuration loading for the radar loop."""

from __future__ import annotations

import copy
import json
import pathlib


ROOT = pathlib.Path(__file__).resolve().parents[1]
DEFAULT_SETTINGS_PATH = ROOT / "config" / "settings.example.json"


DEFAULT_SETTINGS = {
    "mode": "paper",
    "allow_live_trading": False,
    "account_capabilities": {
        "crypto_derivatives": True,
        "crypto_spot": True,
        "spot_borrow": False,
        "options": False,
        "futures": False,
        "prediction_markets": False,
    },
    "scanner": {
        "scan_universe": 100,
        "review_top": 25,
        "min_base_score": 35.0,
        "max_new_paper_trades": 5,
        "hold_minutes": 60,
        "enable_global_proxy_scan": True,
        "enable_global_market_discovery_scan": True,
        "enable_prediction_market_scan": True,
        "enable_crypto_venue_health_scan": True,
        "global_review_top": 40,
        "global_market_discovery_review_top": 75,
        "prediction_review_top": 40,
        "paper_trade_conditional": True,
        "enable_frontier_crypto_adapter_scan": True,
        "frontier_crypto_review_top": 40,
    },
    "global_market_discovery_scanner": {
        "enabled": True,
        "min_discovery_priority": 70,
        "max_surfaces_per_cycle": 28,
        "max_proxy_symbols_per_surface": 4,
        "workers": 12,
        "merge_default_seeds": True,
        "watch_only_stale_minutes": 180,
        "priceable_candidate_score_floor": 42.0,
    },
    "paper_hold_optimizer": {
        "enabled": True,
        "default_hold_minutes": 60,
        "candidate_horizons_minutes": [5, 15, 60, 240],
        "min_samples": 12,
        "min_avg_uplift_bps": 2.0,
        "switch_uplift_bps": 6.0,
        "max_horizon_steps_per_update": 1,
        "recency_weighting_enabled": True,
        "recency_half_life_days": 3.0,
        "confidence_adjustment_enabled": True,
        "confidence_target_effective_samples": 48.0,
        "confidence_floor": 0.25,
        "prefer_shorter_on_tie_bps": 1.0,
        "group_hierarchy": ["signal_key", "venue_trade_direction", "trade_direction"],
    },
    "frontier_crypto_adapter": {
        "enabled": True,
        "timeout_seconds": 8,
        "min_dislocation_bps": 12.0,
    },
    "frontier_data_quality": {
        "enabled": True,
        "adaptive_selection": True,
        "max_symbols_per_cycle": 180,
        "max_symbols_per_venue": 24,
        "known_quality_rate_target": 0.25,
        "quality_target_escalation_enabled": True,
        "quality_target_extra_symbols_per_cycle": 120,
        "quality_target_max_symbols_per_cycle": 300,
        "quality_target_max_symbols_per_venue": 32,
        "quality_target_starved_venue_reserve_per_cycle": 90,
        "unknown_quality_reserve_per_cycle": 60,
        "regional_reserve_per_cycle": 50,
        "exploit_variant_reserve_per_cycle": 35,
        "active_variant_enrichment_top": 10,
        "shadow_variant_enrichment_top": 2,
        "shadow_variant_enrichment_variant_cap": 8,
        "starved_venues": [
            "BITGET",
            "KRAKEN",
            "COINBASE",
            "MEXC",
            "BYBIT_SPOT",
            "OKX_SPOT",
            "KUCOIN",
            "GATE",
            "BINANCE_US",
            "LUNO",
            "VALR",
            "BITSO",
            "BUDA",
            "MERCADO_BITCOIN",
            "INDODAX",
        ],
        "starved_venue_min_depth_per_cycle": 4,
        "venue_depth_minimums": {
            "BITSO": 8,
            "COINBASE": 8,
            "KRAKEN": 8,
            "KUCOIN": 8,
            "GATE": 8,
            "BYBIT_SPOT": 8,
            "BINANCE_US": 8,
            "MEXC": 12,
            "BITGET": 12,
            "OKX_SPOT": 16,
            "LUNO": 16,
            "VALR": 16,
            "INDODAX": 16,
            "MERCADO_BITCOIN": 8,
            "BUDA": 8,
        },
        "depth_levels": 50,
        "workers": 16,
        "timeout_seconds": 6,
        "notionals_usd": [100.0, 250.0, 1000.0],
        "conservative_fee_bps_per_side": 10.0,
        "fresh_seconds": 30.0,
        "block_stale_seconds": 90.0,
        "shadow_below_score": 35.0,
        "conditional_below_score": 60.0,
        "min_verified_snapshots_for_regional_candidate": 3,
        "min_regional_quality_score": 70.0,
        "snapshot_retention_rows": 100000,
    },
    "frontier_regional_fx": {
        "enabled": True,
        "cache_ttl_minutes": 60,
        "max_reference_age_hours": 30,
        "timeout_seconds": 10,
        "quotes": ["ARS", "BRL", "CLP", "COP", "GHS", "IDR", "KES", "MXN", "MYR", "NGN", "PEN", "PHP", "SGD", "THB", "ZAR"],
    },
    "risk": {
        "min_liquidity_score": 0.35,
        "max_spread_bps": 8.0,
        "min_net_edge_bps": 2.0,
        "max_abs_24h_move_pct": 60.0,
        "taker_fee_bps_per_leg": 5.0,
        "slippage_bps_per_leg": 3.0,
        "max_open_paper_trades": 20,
    },
    "learning": {
        "enabled": True,
        "min_samples_for_adjustment": 3,
        "max_adjustment_bps": 15.0,
        "score_adjustment_scale": 0.35,
        "horizon_minutes": [5, 15, 60, 240, 1440],
        "max_outcome_delay_seconds": 300,
    },
    "signal_redesign": {
        "enabled": True,
        "trial_cadence_minutes": 15,
        "min_paired_trials": 30,
        "min_observation_hours": 48,
        "min_valid_label_rate": 0.95,
        "max_outcome_delay_seconds": 300,
        "min_opportunity_coverage": 0.30,
        "min_paired_uplift_bps": 5.0,
        "max_win_rate_decline": 0.05,
        "max_worst_decile_regression_bps": 50.0,
        "revert_regression_bps": 8.0,
        "consecutive_passes_to_promote": 2,
        "max_trials_per_loop": 160,
        "max_trials_per_variant_per_loop": 12,
        "max_trials_per_venue_per_loop": 20,
        "min_shadow_trial_quality_score": 35.0,
        "exclude_shadow_trials_with_critical_anomalies": True,
    },
    "okx_signal_research": {
        "enabled": True,
    },
    "prediction_market_scanner": {
        "orderbook_enrichment_top": 30,
        "provider_market_cap": 50,
        "kalshi_market_cap": 50,
    },
    "self_improvement": {
        "enabled": True,
        "process_code_changes_in_radar_loop": False,
        "max_tasks_per_loop": 5,
        "max_policies_per_task": 5,
        "default_policy_trade_ttl": 30,
        "min_eval_closed_trades": 10,
        "promote_min_improvement_bps": 3.0,
        "revert_max_regression_bps": 8.0,
    },
    "llm_bridge": {
        "enabled": True,
        "ingest_recommendations": True,
        "max_recommendations_per_loop": 20,
        "allowed_actions": [
            "propose_build_task",
            "propose_growth_experiment",
            "propose_hunter_directive",
            "request_data_source",
            "request_market_adapter",
            "request_red_team",
            "propose_signal_variant",
            "propose_diagnostic_hypothesis",
            "propose_code_change",
        ],
    },
    "llm_swarm": {
        "enabled": True,
        "auto_run": True,
        "run_in_radar_loop": False,
        "min_minutes_between_runs": 10,
        "max_recommendations_per_run": 20,
        "write_fallback_recommendations_to_inbox": False,
        "cooldown_on_model_unavailable": True,
        "model_failure_cooldown_minutes": 60,
    },
    "evolution_worker": {
        "enabled": True,
        "interval_seconds": 300,
    },
    "research_worker": {
        "enabled": True,
        "global_market_discovery": True,
        "web_research_enabled": True,
        "run_every_evolution_cycle": True,
        "max_candidates_per_run": 80,
        "max_artifacts_per_run": 20,
        "artifact_priority_floor": 70,
        "suppress_implemented_global_discovery_artifacts": True,
        "discovery_seeds": [],
    },
    "autonomous_builder": {
        "enabled": True,
        "auto_run": True,
        "run_in_radar_loop": False,
        "min_minutes_between_runs": 0,
        "lock_stale_minutes": 180,
        "model_tier": "frontier",
        "plan_max_context_chars": 35000,
        "implementation_report_context_chars": 12000,
        "plan_timeout_seconds": 420,
        "implementation_timeout_seconds": 420,
        "plan_reasoning_effort": "max",
        "implementation_reasoning_effort": "high",
        "max_context_chars": 70000,
        "max_report_chars": 12000,
        "max_code_file_chars": 12000,
        "plan_max_output_tokens": 24000,
        "max_output_tokens": 24000,
        "implementation_strategy": "code_evolution_handoff",
        "require_unified_diff": True,
    },
    "code_evolution": {
        "enabled": True,
        "git_release_enabled": True,
        "run_candidate_canary": False,
        "promote_candidate_after_canary": True,
        "workspace_status_names": True,
        "auto_merge_paper_only": True,
        "max_auto_merges_per_loop": 12,
        "require_frontier_model": False,
        "required_model": "openai/gpt-5.6-sol",
        "min_priority": 50,
        "run_full_regression": True,
        "probation_loops": 1,
        "rollback_on_health_failure": True,
        "generate_patch_when_missing": True,
        "local_context_patch_apply": True,
        "repair_patch_when_apply_fails": True,
        "repair_patch_when_sandbox_fails": True,
        "patch_repair_attempts": 3,
        "repair_unknown_paths": True,
        "validate_test_commands": True,
        "reject_orphan_helpers": True,
        "patch_generation_max_file_chars": 20000,
        "patch_generation_max_output_tokens": 16000,
        "install_changed_python_dependencies": True,
        "standard_patch_tier": "fast",
        "high_quality_patch_tier": "standard",
        "high_quality_patch_min_score": 88,
        "repair_patch_tier": "fast",
        "frontier_patch_tier": "frontier",
        "frontier_required_priority": 98,
        "frontier_required_categories": [
            "evolution_loop_improvement",
        ],
        "frontier_waste_guard_enabled": True,
        "frontier_waste_guard_recent": 12,
        "frontier_waste_guard_after": 8,
        "frontier_waste_guard_min_quality": 55,
    },
    "okx_carry_economics": {
        "default_funding_interval_hours": 8.0,
        "default_taker_fee_bps_per_leg": 5.0,
        "default_slippage_bps_per_leg": 3.0,
        "unknown_borrow_cost_penalty_bps": 25.0,
        "min_positive_net_carry_bps": 3.0,
    },
    "hunter_directive_hygiene": {
        "enabled": True,
    },
    "hunter_allocation": {
        "enabled": True,
        "apply_to_candidate_review": True,
        "buckets": {"exploit": 0.5, "explore": 0.3, "diagnose": 0.2},
    },
    "route_unblocker": {
        "enabled": True,
        "allow_paper_proxy_routes": True,
        "spot_borrow_proxy_allocation_multiplier": 0.25,
        "prediction_market_research_allocation_multiplier": 0.10,
    },
    "signal_safety": {
        "enabled": True,
        "min_closed_for_action": 5,
        "recent_trade_window": 10,
        "quarantine_recent_avg_bps": -100.0,
        "quarantine_lifetime_avg_bps": -250.0,
        "quarantine_worst_bps": -1000.0,
        "quarantine_win_rate": 0.30,
        "demote_recent_avg_bps": -20.0,
        "demote_lifetime_avg_bps": -50.0,
        "demote_win_rate": 0.30,
        "recovery_probe_every_reviews": 25,
        "recovery_probe_allocation_multiplier": 0.10,
        "probation_allocation_multiplier": 0.25,
        "release_min_recovery_trades": 5,
        "release_min_avg_pnl_bps": 10.0,
        "release_min_win_rate": 0.55,
        "release_max_worst_bps": -500.0,
    },
    "contextual_failure_filters": {
        "enabled": True,
        "create_policies": True,
        "min_closed_for_filter": 5,
        "max_new_policies_per_loop": 3,
        "max_active_policies_per_signal": 4,
        "default_policy_trade_ttl": 30,
        "policy_priority": 91,
        "recovery_probe_every_reviews": 25,
        "recovery_probe_allocation_multiplier": 0.10,
        "release_min_recovery_trades": 5,
        "release_min_avg_pnl_bps": 10.0,
        "release_min_win_rate": 0.55,
        "release_max_worst_bps": -500.0,
    },
}


def deep_merge(base: dict, override: dict) -> dict:
    result = copy.deepcopy(base)
    for key, value in override.items():
        if isinstance(value, dict) and isinstance(result.get(key), dict):
            result[key] = deep_merge(result[key], value)
        else:
            result[key] = value
    return result


def load_settings(path: str | pathlib.Path | None = None) -> dict:
    if path is None:
        path = DEFAULT_SETTINGS_PATH
    config_path = pathlib.Path(path)
    if not config_path.exists():
        return copy.deepcopy(DEFAULT_SETTINGS)
    loaded = json.loads(config_path.read_text(encoding="utf-8-sig"))
    return deep_merge(DEFAULT_SETTINGS, loaded)

