"""Configuration loading for the radar loop."""

from __future__ import annotations

import copy
import json
import pathlib


ROOT = pathlib.Path(__file__).resolve().parents[1]
DEFAULT_SETTINGS_PATH = ROOT / "config" / "settings.example.json"
LOCAL_SETTINGS_PATH = ROOT / "config" / "settings.local.json"


DEFAULT_SETTINGS = {
    "mode": "paper",
    "allow_live_trading": False,
    "account_capabilities": {
        "crypto_derivatives": True,
        "crypto_spot": True,
        "spot_borrow": False,
        "options": False,
        "futures": False,
        "prediction_markets": False,
    },
    "scanner": {
        "scan_universe": 500,
        "review_top": 250,
        "min_base_score": 35.0,
        "max_new_paper_trades": 50,
        "hold_minutes": 60,
        "enable_global_proxy_scan": True,
        "enable_global_market_discovery_scan": True,
        "enable_prediction_market_scan": True,
        "enable_crypto_venue_health_scan": True,
        "global_review_top": 100,
        "global_market_discovery_review_top": 150,
        "prediction_review_top": 100,
        "paper_trade_conditional": True,
        "enable_frontier_crypto_adapter_scan": True,
        "frontier_crypto_review_top": 120,
    },
    "paper_context_cost_floor": {
        "enabled": True,
        "safety_multiplier": 1.25,
        "base_cost_bps": 1.0,
        "spread_weight": 1.0,
        "max_liquidity_penalty_bps": 6.0,
        "volatility_weight": 0.08,
        "max_volatility_penalty_bps": 12.0,
        "freshness_penalty_bps_per_window": 2.0,
        "max_freshness_penalty_bps": 12.0,
        "frontier_freshness_window_seconds": 30.0,
        "proxy_freshness_window_seconds": 900.0,
        "extra_leg_cost_bps": 4.0,
        "missing_spread_penalty_bps": 4.0,
        "missing_liquidity_penalty_bps": 3.0,
        "missing_freshness_penalty_bps": 2.0,
        "minimum_score_multiplier": 0.5,
    },
    "yahoo_proxy_reuse_gate": {
        "enabled": True,
        "max_quote_age_seconds": 1200.0,
        "max_expected_bar_lag_seconds": 120.0,
        "default_bar_interval_seconds": 900.0,
        "min_opening_gap_bps": 40.0,
        "min_opening_gap_followthrough_ratio": 0.25,
    },
    "paper_cell_policy": {
        "min_closed_trades": 3,
        "probation_ttl_days": 7,
        "promote_min_avg_pnl_bps": 1.0,
        "promote_min_win_rate": 0.5,
        "revert_avg_pnl_bps": -5.0,
        "asymmetric_direction_min_closed_trades": 20,
        "asymmetric_direction_min_avg_pnl_bps": 1.0,
    },
    "global_market_discovery_scanner": {
        "enabled": True,
        "active_paper_cohort_enabled": True,
        "min_discovery_priority": 70,
        "max_surfaces_per_cycle": 28,
        "max_proxy_symbols_per_surface": 4,
        "recent_discovery_rotation_slots": 8,
        "workers": 12,
        "merge_default_seeds": True,
        "watch_only_stale_minutes": 180,
        "priceable_candidate_score_floor": 42.0,
    },
    "paper_hold_optimizer": {
        "enabled": True,
        "default_hold_minutes": 60,
        "candidate_horizons_minutes": [5, 15, 60, 240],
        "min_samples": 12,
        "min_avg_uplift_bps": 2.0,
        "switch_uplift_bps": 6.0,
        "max_horizon_steps_per_update": 1,
        "recency_weighting_enabled": True,
        "recency_half_life_days": 3.0,
        "confidence_adjustment_enabled": True,
        "confidence_target_effective_samples": 48.0,
        "confidence_floor": 0.25,
        "prefer_shorter_on_tie_bps": 1.0,
        "group_hierarchy": ["signal_key", "venue_trade_direction", "trade_direction"],
    },
    "frontier_crypto_adapter": {
        "enabled": True,
        "timeout_seconds": 8,
        "min_dislocation_bps": 12.0,
        "bybit_region_blocked_probe_interval_seconds": 300,
    },
    "frontier_data_quality": {
        "enabled": True,
        "adaptive_selection": True,
        "max_symbols_per_cycle": 180,
        "max_symbols_per_venue": 24,
        "known_quality_rate_target": 0.25,
        "quality_target_escalation_enabled": True,
        "quality_target_extra_symbols_per_cycle": 120,
        "quality_target_max_symbols_per_cycle": 300,
        "quality_target_max_symbols_per_venue": 32,
        "quality_target_starved_venue_reserve_per_cycle": 90,
        "unknown_quality_reserve_per_cycle": 60,
        "regional_reserve_per_cycle": 50,
        "exploit_variant_reserve_per_cycle": 35,
        "active_variant_enrichment_top": 10,
        "shadow_variant_enrichment_top": 2,
        "shadow_variant_enrichment_variant_cap": 8,
        "starved_venues": [
            "BITGET",
            "KRAKEN",
            "COINBASE",
            "MEXC",
            "BYBIT_SPOT",
            "OKX_SPOT",
            "KUCOIN",
            "GATE",
            "BINANCE_US",
            "LUNO",
            "VALR",
            "BITSO",
            "BUDA",
            "MERCADO_BITCOIN",
            "INDODAX",
            "BITKUB",
            "COINJAR",
            "RIPIO",
            "WHITEBIT",
        ],
        "starved_venue_min_depth_per_cycle": 4,
        "venue_depth_minimums": {
            "BITSO": 8,
            "COINBASE": 8,
            "KRAKEN": 8,
            "KUCOIN": 8,
            "GATE": 8,
            "BYBIT_SPOT": 8,
            "BINANCE_US": 8,
            "MEXC": 12,
            "BITGET": 12,
            "OKX_SPOT": 16,
            "LUNO": 16,
            "VALR": 16,
            "INDODAX": 16,
            "MERCADO_BITCOIN": 8,
            "BUDA": 8,
            "BITKUB": 8,
            "COINJAR": 8,
            "RIPIO": 1,
            "WHITEBIT": 12,
        },
        "depth_levels": 50,
        "workers": 16,
        "timeout_seconds": 6,
        "notionals_usd": [100.0, 250.0, 1000.0],
        "conservative_fee_bps_per_side": 10.0,
        "fresh_seconds": 30.0,
        "block_stale_seconds": 90.0,
        "shadow_below_score": 35.0,
        "conditional_below_score": 60.0,
        "min_verified_snapshots_for_regional_candidate": 3,
        "min_regional_quality_score": 70.0,
        "snapshot_retention_rows": 100000,
        "valid_empty_book_cooldown_after": 2,
        "empty_book_core_asset_exemptions": ["BTC", "ETH", "USDT", "USDC"],
    },
    "frontier_regional_fx": {
        "enabled": True,
        "cache_ttl_minutes": 60,
        "max_reference_age_hours": 30,
        "timeout_seconds": 10,
        "quotes": ["ARS", "AUD", "BRL", "CLP", "COP", "EUR", "GBP", "GHS", "IDR", "KES", "MXN", "MYR", "NGN", "PEN", "PHP", "SGD", "THB", "ZAR"],
    },
    "public_market_adapters": {
        "enabled": True,
        "workers": 5,
        "twse_daily_public": {"enabled": True, "cache_minutes": 60, "max_instruments": 300},
        "kase_futures_public_results": {"enabled": True, "cache_minutes": 15},
        "nzx_gdt_event_reference": {"enabled": True, "cache_minutes": 60},
        "bursa_derivatives_contract_catalog": {"enabled": True, "cache_minutes": 360},
        "bahrain_cross_listings_catalog": {"enabled": True, "cache_minutes": 360},
        "whitebit_perpetuals_public": {
            "enabled": True,
            "cache_minutes": 2,
            "max_instruments": 120,
            "max_depth_books": 16,
            "depth_levels": 50,
        },
        "deribit_derivatives_public": {
            "enabled": True,
            "cache_minutes": 2,
            "currencies": ["BTC", "ETH", "USDC"],
            "max_futures_per_currency": 40,
            "max_options_per_currency": 40,
            "max_depth_books": 6,
            "depth_levels": 20,
        },
    },
    "derivatives_market_adapters": {
        "min_abs_funding_bps": 3.0,
        "min_net_carry_edge_bps": 2.0,
        "min_quality_score": 60.0,
        "fee_bps_per_side": 5.0,
        "slippage_bps_per_side": 3.0,
    },
    "market_admission": {
        "enabled": True,
        "bridge_max_actions_per_loop": 50,
        "consecutive_failures_degraded": 5,
        "diagnostic_after_eligible_scans": 30,
        "implementation_task_after_eligible_scans": 120,
        "requested_symbols": [
            "VIXY", "VXX", "UVXY", "SVXY", "EWY", "PKX", "EWT", "TSM", "UMC",
            "EWZ", "NU", "SHOP", "TD", "RY", "GLD", "SLV", "SPY", "EWJ", "BHP",
        ],
    },
    "risk": {
        "min_liquidity_score": 0.35,
        "max_spread_bps": 8.0,
        "min_net_edge_bps": 2.0,
        "max_abs_24h_move_pct": 60.0,
        "taker_fee_bps_per_leg": 5.0,
        "slippage_bps_per_leg": 3.0,
        "max_open_paper_trades": 500,
    },
    "learning": {
        "enabled": True,
        "min_samples_for_adjustment": 3,
        "max_adjustment_bps": 15.0,
        "score_adjustment_scale": 0.35,
        "horizon_minutes": [5, 15, 60, 240, 1440],
        "max_outcome_delay_seconds": 300,
    },
    "agent_memory": {
        "enabled": True,
        "retrieval_mode": "hybrid_temporal_fts_graph",
        "retrieval_limit_per_agent": 24,
        "retrieval_candidate_pool": 160,
        "max_memory_summary_chars": 800,
        "historical_context_fraction": 0.17,
        "graph_relation_bonus": 0.08,
        "preferred_namespace_fraction": 0.67,
        "recency_half_life_days": 14.0,
        "profile_version_hours": 6.0,
        "minimum_importance": 0.15,
        "legacy_bootstrap_enabled": True,
        "legacy_bootstrap_limit": 20000,
        "retrieval_log_retention_rows": 10000,
        "checkpoint_enabled": True,
        "checkpoint_path": "runs/langgraph_checkpoints.sqlite",
        "checkpoint_retention_cycles": 48,
        "checkpoint_max_storage_mb": 64,
        "checkpoint_compact_on_prune": True,
        "checkpoint_vacuum_min_reclaim_mb": 16,
        "graphiti": {
            "mode": "auto",
            "uri_env": "GRAPHITI_URI",
            "user_env": "GRAPHITI_USER",
            "password_env": "GRAPHITI_PASSWORD",
            "minimum_importance": 0.8,
            "max_episodes_per_cycle": 10,
            "search_enabled": True,
            "max_search_results_per_agent": 6,
        },
    },
    "signal_redesign": {
        "enabled": True,
        "trial_cadence_minutes": 15,
        "min_paired_trials": 30,
        "min_observation_hours": 48,
        "min_valid_label_rate": 0.95,
        "max_outcome_delay_seconds": 300,
        "min_opportunity_coverage": 0.30,
        "min_paired_uplift_bps": 5.0,
        "max_win_rate_decline": 0.05,
        "max_worst_decile_regression_bps": 50.0,
        "revert_regression_bps": 8.0,
        "consecutive_passes_to_promote": 2,
        "max_trials_per_loop": 160,
        "max_trials_per_variant_per_loop": 12,
        "max_trials_per_venue_per_loop": 20,
        "min_shadow_trial_quality_score": 35.0,
        "exclude_shadow_trials_with_critical_anomalies": True,
    },
    "strategy_lab": {
        "enabled": True,
        "observation_programs_enabled": True,
        "promoted_signal_plugins_enabled": True,
        "feature_snapshot_minutes": 5,
        "feature_snapshot_retention_days": 14,
        "feature_snapshot_max_rows": 2_000_000,
        "feature_history_max_points": 4032,
        "max_candidates_per_loop": 100,
        "max_candidates_per_experiment": 10,
        "runtime_review_reserved_slots": 50,
        "candidate_score_bonus": 1.0,
        "max_candidate_score_bonus": 5.0,
        "evaluation_horizon_minutes": 60,
        "expand_min_labels": 12,
        "expand_min_avg_pnl_bps": 6.0,
        "expand_min_win_rate": 0.52,
        "promote_min_labels": 30,
        "promote_min_active_hours": 48.0,
        "promote_min_avg_pnl_bps": 10.0,
        "promote_min_win_rate": 0.53,
        "promote_min_valid_label_rate": 0.90,
        "promote_worst_decile_floor_bps": -45.0,
        "retire_min_labels": 20,
        "retire_max_avg_pnl_bps": -8.0,
        "retire_max_win_rate": 0.43,
        "consecutive_passes_to_promote": 2,
    },
    "okx_signal_research": {
        "enabled": True,
    },
    "prediction_market_scanner": {
        "orderbook_enrichment_top": 30,
        "provider_market_cap": 100,
        "polymarket_market_cap": 100,
        "kalshi_market_cap": 50,
    },
    "self_improvement": {
        "enabled": True,
        "process_code_changes_in_radar_loop": False,
        "max_tasks_per_loop": 5,
        "max_policies_per_task": 5,
        "default_policy_trade_ttl": 30,
        "min_eval_closed_trades": 10,
        "promote_min_improvement_bps": 3.0,
        "revert_max_regression_bps": 8.0,
    },
    "llm_bridge": {
        "enabled": True,
        "ingest_recommendations": True,
        "max_recommendations_per_loop": 20,
        "allowed_actions": [
            "propose_build_task",
            "propose_growth_experiment",
            "propose_hunter_directive",
            "request_data_source",
            "request_market_adapter",
            "request_red_team",
            "propose_signal_variant",
            "propose_diagnostic_hypothesis",
            "propose_strategy_lab_experiment",
            "propose_code_change",
            "spawn_agent",
        ],
    },
    "llm_swarm": {
        "enabled": True,
        "auto_run": True,
        "run_in_radar_loop": False,
        "min_minutes_between_runs": 10,
        "max_recommendations_per_run": 20,
        "write_fallback_recommendations_to_inbox": False,
        "cooldown_on_model_unavailable": True,
        "model_failure_cooldown_minutes": 60,
    },
    "dynamic_agents": {
        "enabled": True,
        "bootstrap_seed_agents": True,
        "adaptive_concurrency": 8,
        "minimum_concurrency": 1,
        "latency_backoff_seconds": 120,
        "memory_backoff_percent": 85,
        "report_limit": 100,
    },
    "evolution_worker": {
        "enabled": True,
        "interval_seconds": 300,
        "defer_generic_builder_when_targeted_code_attempted": True,
    },
    "adapter_implementation_owner": {
        "enabled": True,
        "min_minutes_between_attempts": 15,
        "scan_limit": 100,
    },
    "strategy_implementation_owner": {
        "enabled": True,
        "lease_seconds": 2400,
        "retry_backoff_seconds": 300,
        "memory_context_chars": 70000,
        "memory_retrieval_limit": 80,
        "salvage_invalid_backlog": True,
        "salvage_limit_per_cycle": 12,
        "stalled_testing_hours": 24,
        "report_limit": 100,
    },
    "research_worker": {
        "enabled": True,
        "global_market_discovery": True,
        "web_research_enabled": True,
        "run_every_evolution_cycle": True,
        "bootstrap_seed_catalog_once": True,
        "search_themes_per_cycle": 2,
        "search_theme_cooldown_hours": 168,
        "max_web_discoveries_per_cycle": 8,
        "require_public_source_urls": True,
        "model_tier": "fast",
        "reasoning_effort": "low",
        "max_output_tokens": 5000,
        "timeout_seconds": 120,
        "max_candidates_per_run": 80,
        "max_artifacts_per_run": 20,
        "artifact_priority_floor": 70,
        "discovery_seeds": [],
    },
    "autonomous_builder": {
        "enabled": True,
        "auto_run": True,
        "run_in_radar_loop": False,
        "min_minutes_between_runs": 20,
        "lock_stale_minutes": 180,
        "model_tier": "standard",
        "plan_max_context_chars": 35000,
        "implementation_report_context_chars": 12000,
        "plan_timeout_seconds": 240,
        "implementation_timeout_seconds": 240,
        "plan_reasoning_effort": "medium",
        "implementation_reasoning_effort": "medium",
        "max_context_chars": 70000,
        "max_report_chars": 12000,
        "max_code_file_chars": 12000,
        "plan_max_output_tokens": 12000,
        "max_output_tokens": 12000,
        "implementation_strategy": "code_evolution_handoff",
        "require_unified_diff": True,
    },
    "codex_repo_agent": {
        "enabled": True,
        "model": "gpt-5.6-sol",
        "reasoning_effort": "high",
        "timeout_seconds": 1800,
        "resume_cooldown_seconds": 300,
        "max_resumes_per_cycle": 1,
        "post_promotion_health_grace_seconds": 600,
        "post_promotion_health_loops": 3,
        "runtime_package": "openai-codex==0.144.4",
        "npm_runtime_package": "@openai/codex@0.146.0",
        "npm_fallback_enabled": True,
        "auto_install_npm_fallback": False,
        "network_access": True,
        "api_key_envs": ["CODEX_API_KEY", "OPENAI_API_KEY"],
    },
    "code_evolution": {
        "enabled": True,
        "git_release_enabled": True,
        "run_candidate_canary": False,
        "promote_candidate_after_canary": True,
        "workspace_status_names": True,
        "auto_merge_paper_only": True,
        "max_auto_merges_per_loop": 12,
        "require_frontier_model": False,
        "required_model": "openai/gpt-5.6-sol",
        "min_priority": 50,
        "run_full_regression": True,
        "probation_loops": 1,
        "rollback_on_health_failure": True,
        "generate_patch_when_missing": True,
        "local_context_patch_apply": True,
        "repair_patch_when_apply_fails": True,
        "repair_patch_when_sandbox_fails": True,
        "patch_repair_attempts": 3,
        "repair_unknown_paths": True,
        "validate_test_commands": True,
        "reject_orphan_helpers": True,
        "patch_generation_max_file_chars": 20000,
        "patch_generation_max_output_tokens": 16000,
        "install_changed_python_dependencies": True,
        "standard_patch_tier": "fast",
        "high_quality_patch_tier": "standard",
        "high_quality_patch_min_score": 88,
        "repair_patch_tier": "fast",
        "frontier_patch_tier": "frontier",
        "frontier_required_priority": 98,
        "frontier_required_categories": [
            "evolution_loop_improvement",
        ],
        "frontier_waste_guard_enabled": True,
        "frontier_waste_guard_recent": 12,
        "frontier_waste_guard_after": 8,
        "frontier_waste_guard_min_quality": 55,
    },
    "okx_carry_economics": {
        "default_funding_interval_hours": 8.0,
        "default_taker_fee_bps_per_leg": 5.0,
        "default_slippage_bps_per_leg": 3.0,
        "unknown_borrow_cost_penalty_bps": 25.0,
        "min_positive_net_carry_bps": 3.0,
    },
    "hunter_directive_hygiene": {
        "enabled": True,
    },
    "hunter_allocation": {
        "enabled": True,
        "apply_to_candidate_review": True,
        "buckets": {"exploit": 0.5, "explore": 0.3, "diagnose": 0.2},
    },
    "route_unblocker": {
        "enabled": True,
        "allow_paper_proxy_routes": True,
        "spot_borrow_proxy_allocation_multiplier": 0.25,
        "prediction_market_research_allocation_multiplier": 0.10,
    },
    "signal_safety": {
        "enabled": True,
        "min_closed_for_action": 5,
        "recent_trade_window": 10,
        "quarantine_recent_avg_bps": -100.0,
        "quarantine_lifetime_avg_bps": -250.0,
        "quarantine_worst_bps": -1000.0,
        "quarantine_win_rate": 0.30,
        "demote_recent_avg_bps": -20.0,
        "demote_lifetime_avg_bps": -50.0,
        "demote_win_rate": 0.30,
        "recovery_probe_every_reviews": 25,
        "recovery_probe_allocation_multiplier": 0.10,
        "probation_allocation_multiplier": 0.25,
        "release_min_recovery_trades": 5,
        "release_min_avg_pnl_bps": 10.0,
        "release_min_win_rate": 0.55,
        "release_max_worst_bps": -500.0,
    },
    "contextual_failure_filters": {
        "enabled": True,
        "create_policies": True,
        "min_closed_for_filter": 5,
        "max_new_policies_per_loop": 3,
        "max_active_policies_per_signal": 4,
        "default_policy_trade_ttl": 30,
        "policy_priority": 91,
        "recovery_probe_every_reviews": 25,
        "recovery_probe_allocation_multiplier": 0.10,
        "release_min_recovery_trades": 5,
        "release_min_avg_pnl_bps": 10.0,
        "release_min_win_rate": 0.55,
        "release_max_worst_bps": -500.0,
    },
}


def deep_merge(base: dict, override: dict) -> dict:
    result = copy.deepcopy(base)
    for key, value in override.items():
        if isinstance(value, dict) and isinstance(result.get(key), dict):
            result[key] = deep_merge(result[key], value)
        else:
            result[key] = value
    return result


def load_settings(path: str | pathlib.Path | None = None) -> dict:
    if path is None:
        path = DEFAULT_SETTINGS_PATH
    config_path = pathlib.Path(path)
    if not config_path.exists():
        settings = copy.deepcopy(DEFAULT_SETTINGS)
    else:
        loaded = json.loads(config_path.read_text(encoding="utf-8-sig"))
        settings = deep_merge(DEFAULT_SETTINGS, loaded)
    if path == DEFAULT_SETTINGS_PATH and LOCAL_SETTINGS_PATH.exists():
        local_loaded = json.loads(LOCAL_SETTINGS_PATH.read_text(encoding="utf-8-sig"))
        settings = deep_merge(settings, local_loaded)
    return settings

